---
title: "Project Milestones"
editor:
  render-on-save: true
---

::: callout-note
The purpose of the milestones is to help you monitoring your progress throughout the semester.

In each milestone session, each project group briefly presents their current process and we can discuss open questions (approx. 1 min presentation + 3 min discussion per group).

For this purpose, each group is supposed to prepare **1 slide** (singular!) for each of the milestones and **upload them on Ilias until midnight before the respective session.**
:::

::: callout-important
Check out the [schedule](schedule.qmd) for the actual dates.
:::


::: {.callout-caution collapse="true" icon="false"}

### Milestone 1: Paper+Dataset selected {#sec-ms1}
**Goals to be reached:**

-   You selected a paper and a dataset to replicate
-   You extracted the central hypotheses of the paper

**Slides:**
Prepare 1 Slide showing:

- Teamname + Members
- The general idea of the experiment
- The main research question
- The main analysis you will perform (ERP, Time-Frequency, Source-space, others)

:::: callout-tip
Research questions can often be answered by a "yes" or "no".
::::

:::

::: {.callout-caution collapse="true" icon="false"}
### Milestone 2: Processing Pipeline {#sec-ms2}
**Goals to be reached:**

- Map out the required analysis pipeline of the authors
- Compare this to the analysis pipeline you want to do (it should not be identical!)
- Downloaded + Loaded the data. Show a first impression of the continuous data of one subject.

**Slides:**
Prepare 1 slide showing:

- The central research question (one sentence, very brief)
- A table contrasting the authors and your pipeline
- A plot of the continuous EEG data with events marked

:::: callout-warning
Not all authors do a good job to clearly communicate how their pipeline looked like. Add notes and ask, when you are unsure!
:::: 

:::: callout-note
It is totally fine to adapt your processing pipeline as you go & experience problems / successes and get feedback.
::::

:::


::: {.callout-caution collapse="true" icon="false"}
### Milestone 3: First subject analyzed {#sec-ms3}
**Goals to be reached:**

- Implemented a preprocessing pipeline
- One single subject is analyzed
 
**Slides:**
Prepare 1 slide showing:
- The table with the authors and your improved pipeline - highlight changes.
- First results of one subject (e.g. an ERP, TRF or similar)

:::


::: {.callout-caution collapse="true" icon="false"}
### Milestone 4: All subjects {#sec-ms4}
**Goals to be reached:**  

- Your pipeline worked for all subjects
- Further outliers / problems  identified

**Slides:**
Provide 1-2 slides with results of your sanity checks.

Sanity checks could be (depending on project, come up with your own!)  
- ICA topographies
- ERPs including baseline
- Comparisons to author results


:::

::: {.callout-caution collapse="true" icon="false"}
### Milestone 5: Outlook {#sec-ms5}
**Goals to be reached:**  

- You should by now have replicated (or not!) the results of the authors
- You now think of an additional analysis (e.g. ERP, decoding, linear model, time-frequency, source-space) to run on this dataset.

**Slides:** Prepare 2 slides listing:  

- (Slide 1) the current state of replication vs. not
- (Slide 2) your ideas on what to look at next

:::

