---
title: "Schedule WS2026"

editor:
  render-on-save: true
---

::: callout-note
An entry in the table means:

-   Lecture, exercise: watch/submit them by that weekly meeting (i.e. Wednesday, 09:45 am).
-   Milestone: upload the presentation slide until 10:00 on the Monday before the weekly meeting. Attend the weekly meeting for milestone presentation & discussion.
:::

+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| .       | Date       | Special-Session | Watch this:                                                                                                  | Submit this:                                                                                                 | Deliver this:                                                                                                | benchmark (Fri)                                                                                              |
+=========+============+=================+==============================================================================================================+==============================================================================================================+==============================================================================================================+==============================================================================================================+
| 01      | 14.10.2026 | Intro,          | Introduction to Neuroimaging (video 1.8)                                                                     |                                                                                                              |                                                                                                              | Introduction                                                                                                 |
|         |            |                 |                                                                                                              |                                                                                                              |                                                                                                              |                                                                                                              |
|         |            | Organisation    |                                                                                                              |                                                                                                              |                                                                                                              |                                                                                                              |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 02      | 21.10.2026 |                 | Introduction to Neuroimaging (all videos)                                                                    | E-1: My first ERP                                                                                            | Group-Names + Members                                                                                        | BIDS                                                                                                         |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 03      | 28.10.2026 |                 | ERPs                                                                                                         | E-2: Tanaka ERP                                                                                              | Milestone 1: Paper+Dataset selected                                                                          | EEG Analysis                                                                                                 |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 04      | 04.11.2026 | canceled        | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} |                                                                                                              |
|         |            |                 | .                                                                                                            | .                                                                                                            | .                                                                                                            |                                                                                                              |
|         |            |                 | :::                                                                                                          | :::                                                                                                          | :::                                                                                                          |                                                                                                              |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 05      | 11.11.2026 |                 | Filter + Referencing                                                                                         | E-3: Filtering                                                                                               |                                                                                                              | Typical pipeline                                                                                             |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 06      | 18.11.2026 |                 | Data Cleaning                                                                                                | E-4: Cleaning                                                                                                |                                                                                                              |                                                                                                              |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 07      | 25.11.2026 |                 | Blind Source Separation                                                                                      | E-5: ICA                                                                                                     | Milestone 2: Processing Pipeline                                                                             | ICA                                                                                                          |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 08      | 02.12.2026 |                 | Statistics + Multiple Linear Regression                                                                      | E-6: Linear Models                                                                                           |                                                                                                              | Replication, Pt.1                                                                                            |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 09      | 09.12.2026 |                 | Encoding Models                                                                                              | E-7: Encoding models                                                                                         |                                                                                                              | Replication, Pt.2                                                                                            |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 10      | 16.12.2026 |                 | Multiple Comparisons                                                                                         | E-8: Cluster Permutation Tests                                                                               | Milestone 3: First subject analyzed                                                                          |                                                                                                              |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 11      | 23.12.2026 | Holidays        | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} |
|         |            |                 | .                                                                                                            | .                                                                                                            | .                                                                                                            | .                                                                                                            |
|         |            |                 | :::                                                                                                          | :::                                                                                                          | :::                                                                                                          | :::                                                                                                          |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 12      | 30.12.2026 | Holidays        | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} |
|         |            |                 | .                                                                                                            | .                                                                                                            | .                                                                                                            | .                                                                                                            |
|         |            |                 | :::                                                                                                          | :::                                                                                                          | :::                                                                                                          | :::                                                                                                          |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 13      | 06.01.2027 | Holidays        | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} | ::: {style="background: linear-gradient(to top right, #fff calc(50% - 1px), black , #fff calc(50% + 1px) )"} |                                                                                                              |
|         |            |                 | .                                                                                                            | .                                                                                                            | .                                                                                                            |                                                                                                              |
|         |            |                 | :::                                                                                                          | :::                                                                                                          | :::                                                                                                          |                                                                                                              |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 14      | 13.01.2027 |                 | Time Frequency                                                                                               | E-9: Timefrequency                                                                                           |                                                                                                              |                                                                                                              |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 15      | 20.01.2027 |                 | Decoding / RSA / BCI                                                                                         | E-10: Decoding                                                                                               |                                                                                                              |                                                                                                              |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 16      | 27.01.2027 |                 | Source Localization                                                                                          | E-11: Source Localization                                                                                    | Milestone 4 : All subjects                                                                                   |                                                                                                              |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 17      | 03.02.2027 |                 |                                                                                                              |                                                                                                              |                                                                                                              | Guide on posters                                                                                             |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+
| 18      | 10.02.2027 |                 | Other Topics + Outlook                                                                                       |                                                                                                              | Milestone 5: Propose further reaching analyses                                                               |                                                                                                              |
+---------+------------+-----------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+

::: callout-note
The [poster](semesterproject.qmd#deadline) is due: 31.03.2026 (TBD).
:::